### ISSUE TITLE
Create Windows version

### ISSUE THREAD

**Issue by MaickonPrebianca** [PerryWerneck/python3-tn3270#1]
Access via module ctypes Python

**Comment by PerryWerneck** [comment]
Issue moved to python bindings project. When complete the windows module will be released here.

**Comment by PerryWerneck** [comment]
Linux code seens to be ok. Researching how to build it for windows.

**Comment by PerryWerneck** [comment]
Extension built using msvc and python 3.7 setuptools, README updated with build instructions.
